const translations = {
    eng: {
        headerTitle: "📊 Habit Tracker",
        headerSubtitle: "Build better habits, one day at a time",
        save: "💾 Save",
        export: "📥 Export",
        import: "📤 Import",
        reset: "🔄 Reset",
        habitInputPlaceholder: "Enter a new habit (e.g., Exercise, Read, Meditate)",
        categoryHealth: "Health",
        categoryLearning: "Learning",
        categoryProductivity: "Productivity",
        categoryWellness: "Wellness",
        categoryOther: "Other",
        addHabit: "+ Add Habit",
        totalHabits: "Total Habits",
        completedToday: "Completed Today",
        currentStreak: "Overall Streak",
        weeklyAverage: "Weekly Average",
        daily: "📋 Daily",
        weekly: "📅 Weekly",
        monthly: "📆 Monthly",
        exp: "EXP",
        progressAnalytics: "Progress Analytics (Line Chart)",
        todayCompletion: "Today's Completion (Pie Chart)",
        completed: "✓ Completed",
        pending: "◯ Pending",
        todayRoutine: "📋 Today's Routine",
        weeklyRoutine: "📅 Weekly Routine",
        monthlyRoutine: "📆 Monthly Routine",
        previous: "← Previous",
        next: "Next →",
        quickActions: "⏰ Quick Actions",
        completeAll: "✓ Complete All Today",
        resetToday: "Reset Today's Progress",
        sortStreak: "Sort by Streak",
        searchHabits: "🔍 Search habits...",
        allCategories: "All Categories",
        yourHabits: "Your Habits",
        noHabits: "No habits yet. Add one to get started!",
        insights: "📈 Insights",
        mostConsistent: "Most Consistent",
        totalCompletions: "Total Completions",
        bestDay: "Best Day",
        successRate: "Success Rate",
        howToUse: "📖 How to Use Habit Tracker",
        gettingStarted: "Getting Started",
        step1: "1. Enter a habit name and select a category",
        step2: "2. Click \"+Add Habit\" to create it",
        step3: "3. Mark habits complete each day by clicking \"Mark Done\"",
        features: "Features",
        routineViews: "Routine Views:",
        routineViewsDesc: "Switch between Daily, Weekly, and Monthly views",
        dayDetails: "Day Details:",
        dayDetailsDesc: "Click any day to see detailed information",
        saveFeature: "Save:",
        saveDesc: "Manually save your data",
        tips: "Tips",
        tip1: "✓ Complete all habits to build momentum",
        tip2: "✓ Keep your streak going every day",
        total: "Total",
        completionRate: "Completion Rate",
        quickAccess: "⚡ Quick Access",
        topConsistentHabits: "Top consistent habits",
        settings: "⚙️ Settings",
        languageSetting: "Language",
        theme: "Dark Theme",
    },
    kor: {
        headerTitle: "📊 습관 추적기",
        headerSubtitle: "더 나은 습관을 매일 만들어보세요",
        save: "💾 저장",
        export: "📥 내보내기",
        import: "📤 가져오기",
        reset: "🔄 초기화",
        habitInputPlaceholder: "새로운 습관을 입력하세요 (예: 운동, 읽기, 명상)",
        categoryHealth: "건강",
        categoryLearning: "학습",
        categoryProductivity: "생산성",
        categoryWellness: "웰빙",
        categoryOther: "기타",
        addHabit: "+ 습관 추가",
        totalHabits: "총 습관",
        completedToday: "오늘 완료",
        currentStreak: "전체 연속",
        weeklyAverage: "주간 평균",
        daily: "📋 일일",
        weekly: "📅 주간",
        monthly: "📆 월간",
        exp: "EXP",
        progressAnalytics: "진행 상황 분석 (선 그래프)",
        todayCompletion: "오늘의 완료율 (원형 차트)",
        completed: "✓ 완료됨",
        pending: "◯ 대기중",
        todayRoutine: "📋 오늘의 루틴",
        weeklyRoutine: "📅 주간 루틴",
        monthlyRoutine: "📆 월간 루틴",
        previous: "← 이전",
        next: "다음 →",
        quickActions: "⏰ 빠른 작업",
        completeAll: "✓ 오늘 모두 완료",
        resetToday: "오늘의 진행 상황 초기화",
        sortStreak: "연속 순으로 정렬",
        searchHabits: "🔍 습관 검색...",
        allCategories: "모든 카테고리",
        yourHabits: "내 습관",
        noHabits: "아직 습관이 없습니다. 하나를 추가하세요!",
        insights: "📈 통계",
        mostConsistent: "가장 꾸준한",
        totalCompletions: "총 완료 수",
        bestDay: "최고의 날",
        successRate: "성공률",
        howToUse: "📖 사용 방법",
        gettingStarted: "시작하기",
        step1: "1. 습관 이름을 입력하고 카테고리를 선택하세요",
        step2: "2. \"+ 습관 추가\"를 클릭하세요",
        step3: "3. \"완료\"를 클릭하여 매일 습관을 표시하세요",
        features: "기능",
        routineViews: "루틴 보기:",
        routineViewsDesc: "일일, 주간 및 월간 보기 사이를 전환하세요",
        dayDetails: "날짜 세부정보:",
        dayDetailsDesc: "자세한 정보를 보려면 어느 날짜든 클릭하세요",
        saveFeature: "저장:",
        saveDesc: "데이터를 수동으로 저장하세요",
        tips: "팁",
        tip1: "✓ 모든 습관을 완료하여 추진력을 키우세요",
        tip2: "✓ 매일 연속을 유지하세요",
        total: "총계",
        completionRate: "완료율",
        quickAccess: "⚡ 빠른 접근",
        topConsistentHabits: "가장 꾸준한 습관",
        settings: "⚙️ 설정",
        languageSetting: "언어",
        theme: "다크 테마",
    },
    jap: {
        headerTitle: "📊 習慣トラッカー",
        headerSubtitle: "毎日より良い習慣を構築してください",
        save: "💾 保存",
        export: "📥 エクスポート",
        import: "📤 インポート",
        reset: "🔄 リセット",
        habitInputPlaceholder: "新しい習慣を入力してください（例：運動、読書、瞑想）",
        categoryHealth: "健康",
        categoryLearning: "学習",
        categoryProductivity: "生産性",
        categoryWellness: "ウェルネス",
        categoryOther: "その他",
        addHabit: "+ 習慣を追加",
        totalHabits: "合計習慣",
        completedToday: "今日完了",
        currentStreak: "全体ストリーク",
        weeklyAverage: "週間平均",
        daily: "📋 日日",
        weekly: "📅 週間",
        monthly: "📆 月間",
        exp: "EXP",
        progressAnalytics: "進捗分析（折れ線グラフ）",
        todayCompletion: "今日の完了率（円グラフ）",
        completed: "✓ 完了",
        pending: "◯ 保留中",
        todayRoutine: "📋 今日のルーティン",
        weeklyRoutine: "📅 週間ルーティン",
        monthlyRoutine: "📆 月間ルーティン",
        previous: "← 前へ",
        next: "次へ →",
        quickActions: "⏰ クイックアクション",
        completeAll: "✓ 今日すべて完了",
        resetToday: "今日の進捗をリセット",
        sortStreak: "ストリークで並べ替え",
        searchHabits: "🔍 習慣を検索...",
        allCategories: "すべてのカテゴリ",
        yourHabits: "あなたの習慣",
        noHabits: "習慣がまだありません。1つ追加してください！",
        insights: "📈 洞察",
        mostConsistent: "最も一貫した",
        totalCompletions: "総完了数",
        bestDay: "最高の日",
        successRate: "成功率",
        howToUse: "📖 使用方法",
        gettingStarted: "はじめに",
        step1: "1. 習慣���を入力してカテゴリを選択してください",
        step2: "2. \"+ 習慣を追加\"をクリックしてください",
        step3: "3. \"完了\"をクリックして毎日習慣をマークしてください",
        features: "機能",
        routineViews: "ルーティン表示:",
        routineViewsDesc: "日間、週間、月間ビューを切り替えます",
        dayDetails: "日付の詳細:",
        dayDetailsDesc: "詳細を表示するには任意の日付をクリックしてください",
        saveFeature: "保存:",
        saveDesc: "データを手動で保存する",
        tips: "ヒント",
        tip1: "✓ すべての習慣を完了して勢いを積み重ねてください",
        tip2: "✓ 毎日ストリークを続けてください",
        total: "合計",
        completionRate: "完了率",
        quickAccess: "⚡ クイックアクセス",
        topConsistentHabits: "最も継続している習慣",
        settings: "⚙️ 設定",
        languageSetting: "言語",
        theme: "ダークテーマ",
    },
    chi: {
        headerTitle: "📊 习惯追踪器",
        headerSubtitle: "每天建立更好的习惯",
        save: "💾 保存",
        export: "📥 导出",
        import: "📤 导入",
        reset: "🔄 重置",
        habitInputPlaceholder: "输入新习惯（例如：运动、阅读、冥想）",
        categoryHealth: "健康",
        categoryLearning: "学习",
        categoryProductivity: "生产力",
        categoryWellness: "健��养生",
        categoryOther: "其他",
        addHabit: "+ 添加习惯",
        totalHabits: "总习惯",
        completedToday: "今天完成",
        currentStreak: "总连续",
        weeklyAverage: "每周平均",
        daily: "📋 每日",
        weekly: "📅 每周",
        monthly: "📆 每月",
        exp: "EXP",
        progressAnalytics: "进度分析（折线图）",
        todayCompletion: "今日完成率（饼图）",
        completed: "✓ 已完成",
        pending: "◯ 待处理",
        todayRoutine: "📋 今日例行",
        weeklyRoutine: "📅 每周例行",
        monthlyRoutine: "📆 每月例行",
        previous: "← 上一步",
        next: "下一步 →",
        quickActions: "⏰ 快速操作",
        completeAll: "✓ 今天全部完成",
        resetToday: "重置今天的进度",
        sortStreak: "按连续排序",
        searchHabits: "🔍 搜索习惯...",
        allCategories: "所有类别",
        yourHabits: "你的习惯",
        noHabits: "还没有习惯。添加一个开始吧！",
        insights: "📈 洞察力",
        mostConsistent: "最坚持",
        totalCompletions: "总完成数",
        bestDay: "最好的日子",
        successRate: "成功率",
        howToUse: "📖 如何使用",
        gettingStarted: "入门",
        step1: "1. 输入习惯名称并选择类别",
        step2: "2. 点击\"+ 添加习惯\"来创建",
        step3: "3. 单击\"完成\"每天标记习惯",
        features: "功能",
        routineViews: "例行查看:",
        routineViewsDesc: "在日间、周间和月间视图之间切换",
        dayDetails: "日期详情:",
        dayDetailsDesc: "单击任何日期查看详细信息",
        saveFeature: "保存:",
        saveDesc: "手动保存您的数据",
        tips: "技巧",
        tip1: "✓ 完成所有习惯以建立动力",
        tip2: "✓ 每天保持连续",
        total: "总计",
        completionRate: "完成率",
        quickAccess: "⚡ 快速访问",
        topConsistentHabits: "最坚持的习惯",
        settings: "⚙️ 设置",
        languageSetting: "语言",
        theme: "深色主题",
    },
    vie: {
        headerTitle: "📊 Trình Theo Dõi Thói Quen",
        headerSubtitle: "Xây dựng những thói quen tốt hơn mỗi ngày",
        save: "💾 Lưu",
        export: "📥 Xuất",
        import: "📤 Nhập",
        reset: "🔄 Đặt Lại",
        habitInputPlaceholder: "Nhập thói quen mới (ví dụ: Tập thể dục, Đọc sách, Thiền)",
        categoryHealth: "Sức Khỏe",
        categoryLearning: "Học Tập",
        categoryProductivity: "Năng Suất",
        categoryWellness: "Sức Khỏe Tinh Thần",
        categoryOther: "Khác",
        addHabit: "+ Thêm Thói Quen",
        totalHabits: "Tổng Thói Quen",
        completedToday: "Hoàn Thành Hôm Nay",
        currentStreak: "Chuỗi Tổng Thể",
        weeklyAverage: "Trung Bình Hàng Tuần",
        daily: "📋 Hàng Ngày",
        weekly: "📅 Hàng Tuần",
        monthly: "📆 Hàng Tháng",
        exp: "EXP",
        progressAnalytics: "Phân Tích Tiến Độ (Biểu Đồ Đường)",
        todayCompletion: "Tỷ Lệ Hoàn Thành Hôm Nay (Biểu Đồ Tròn)",
        completed: "✓ Đã Hoàn Thành",
        pending: "◯ Chờ Xử Lý",
        todayRoutine: "📋 Thói Quen Hôm Nay",
        weeklyRoutine: "📅 Thói Quen Hàng Tuần",
        monthlyRoutine: "📆 Thói Quen Hàng Tháng",
        previous: "← Trước",
        next: "Tiếp Theo →",
        quickActions: "⏰ Hành Động Nhanh",
        completeAll: "✓ Hoàn Thành Tất Cả Hôm Nay",
        resetToday: "Đặt Lại Tiến Độ Hôm Nay",
        sortStreak: "Sắp Xếp Theo Chuỗi",
        searchHabits: "🔍 Tìm Kiếm Thói Quen...",
        allCategories: "Tất Cả Danh Mục",
        yourHabits: "Thói Quen Của Bạn",
        noHabits: "Chưa có thói quen nào. Thêm một thói quen để bắt đầu!",
        insights: "📈 Thông Tin Chi Tiết",
        mostConsistent: "Nhất Quán Nhất",
        totalCompletions: "Tổng Số Lần Hoàn Thành",
        bestDay: "Ngày Tốt Nhất",
        successRate: "Tỷ Lệ Thành Công",
        howToUse: "📖 Cách Sử Dụng",
        gettingStarted: "Bắt Đầu",
        step1: "1. Nhập tên thói quen và chọn danh mục",
        step2: "2. Nhấp vào \"+ Thêm Thói Quen\" để tạo",
        step3: "3. Nhấp vào \"Hoàn Thành\" để đánh dấu thói quen hàng ngày",
        features: "Tính Năng",
        routineViews: "Chế Độ Xem Thói Quen:",
        routineViewsDesc: "Chuyển đổi giữa chế độ xem hàng ngày, hàng tuần và hàng tháng",
        dayDetails: "Chi Tiết Ngày:",
        dayDetailsDesc: "Nhấp vào bất kỳ ngày nào để xem chi tiết",
        saveFeature: "Lưu:",
        saveDesc: "Lưu dữ liệu của bạn theo cách thủ công",
        tips: "Mẹo",
        tip1: "✓ Hoàn thành tất cả thói quen để tạo đà",
        tip2: "✓ Giữ chuỗi của bạn mỗi ngày",
        total: "Tổng Cộng",
        completionRate: "Tỷ Lệ Hoàn Thành",
        quickAccess: "⚡ Truy Cập Nhanh",
        topConsistentHabits: "Thói quen ổn định nhất",
        settings: "⚙️ Cài đặt",
        languageSetting: "Ngôn ngữ",
        theme: "Chế độ tối",
    }
};

class LanguageManager {
    constructor() {
        this.currentLanguage = localStorage.getItem('language') || 'eng';
        this.loadTimezones();
    }

    setLanguage(lang) {
        this.currentLanguage = lang;
        localStorage.setItem('language', lang);
        this.updatePageLanguage();
    }

    updatePageLanguage() {
        const trans = translations[this.currentLanguage];
        
        // Update data-i18n elements
        document.querySelectorAll('[data-i18n]').forEach(element => {
            const key = element.dataset.i18n;
            if (trans[key]) {
                if (element.tagName === 'INPUT' || element.tagName === 'TEXTAREA') {
                    element.placeholder = trans[key];
                } else {
                    element.textContent = trans[key];
                }
            }
        });
    }

    get(key) {
        return translations[this.currentLanguage][key] || key;
    }

    loadTimezones() {
        const timezones = [
            { name: 'GMT/UTC', value: 'UTC' },
            { name: 'GMT+1 (Europe/London)', value: 'Europe/London' },
            { name: 'GMT+2 (Europe/Paris)', value: 'Europe/Paris' },
            { name: 'GMT+9 (Asia/Seoul - KST)', value: 'Asia/Seoul' },
            { name: 'GMT+9 (Asia/Tokyo - JST)', value: 'Asia/Tokyo' },
            { name: 'GMT+8 (Asia/Shanghai - CST)', value: 'Asia/Shanghai' },
            { name: 'GMT+7 (Asia/Ho_Chi_Minh - ICT)', value: 'Asia/Ho_Chi_Minh' },
            { name: 'EST (America/New_York)', value: 'America/New_York' },
            { name: 'PST (America/Los_Angeles)', value: 'America/Los_Angeles' },
            { name: 'IST (Asia/Kolkata)', value: 'Asia/Kolkata' },
            { name: 'AEST (Australia/Sydney)', value: 'Australia/Sydney' }
        ];
        
        const select = document.getElementById('timezoneSelect');
        if (!select) {
            return;
        }
        timezones.forEach(tz => {
            const option = document.createElement('option');
            option.value = tz.value;
            option.textContent = tz.name;
            select.appendChild(option);
        });
    }
}
